version: '3.8'
services:
  besu-mainnet-node:
    image: hyperledger/besu:latest
    container_name: besu-mainnet
    command: >
      --config-file=/config/config-snap-mainnet.toml
      --genesis-file=/config/genesis-mainnet.json
      --rpc-http-api=ETH,NET,WEB3
      --host-allowlist="*"
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8549:8545"
      - "8548:8546"
    volumes:
      - ./data:/var/lib/besu
      - ./config:/config
    restart: unless-stopped
